[package]
name = "self-hosted"
version = "0.1.0"
authors = ["Jacob Hrbek <kreyren@rixotstudio.cz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
